services:
  nginx:
    build:
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`passwort.marcom.one`)"
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true